### PR TITLE
Support for Guzzle 6x

### PR DESCRIPTION
**Pull request by merlingore**
This was @vicdelfant's pull request originally but it seems like he deleted his repo, so recreating it as it passes all the tests and is super useful to support Guzzle 6x.

### CODE REVIEW

**Comment by vicdelfant** [comment]
Ah, my bad! I was under the assumption that the original PR was merged a long time ago - obviously it wasn't. Thanks for re-submitting it!

**Comment by merlingore** [comment]
No worries @vicdelfant, thanks for the work! 😄

**Comment by vargasx** [comment]
@merlingore nice work, thank you, just few comments

**Comment by beck24** [comment]
Seems like this repo isn't getting much love...

Thanks for this fix, tested and working.  Please merge + release so I can keep my composer dependencies using the official version :)

**Comment by luisuribe** [comment]
Thanks! i'll be releasing a new version this week.

**Pull request merged**
